# Generated by Django 3.0.5 on 2020-04-28 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('steps', models.CharField(max_length=1000)),
                ('fact', models.CharField(max_length=100)),
                ('expect', models.CharField(max_length=100)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('open', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('W', 'Ожидание'), ('L', 'Рассматривается'), ('D', 'Отклонено'), ('A', 'Принято'), ('F', 'Исправлено')], max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='reports.Tag')),
            ],
        ),
    ]
